apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-mq-client-cert
spec:
  dnsNames:
    - '*.stock-trader-cluster-3a99165d2acc3a9ca65ba8c534430045-0000.eu-gb.containers.appdomain.cloud'
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - client auth
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: KEY_STORE_PASSWORD
        name: mq-client-jks-password
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-mq-cluster-issuer
  secretName: mq-client-jks
  subject:
    organizations:
    - ibm
