apiVersion: db2u.databases.ibm.com/v1
kind: Db2uCluster
metadata:
  name: trader
  namespace: db2
spec:
  license:
    accept: true
  account:
    privileged: true
    imagePullSecrets:
      - ibm-entitlement-key
  version: "11.5.5.1"
  size: 1
  podConfig:
    db2u:
      resource:
        db2u:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 2
            memory: 4Gi
  environment:
    dbType: db2oltp
    instance:
      password: db2password
  storage:
    - name: meta
      type: "create"
      spec:
        storageClassName: "ibmc-file-gold"
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
    - name: data
      type: "create"
      spec:
        storageClassName: "ibmc-block-gold"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
