apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: self-signed-ca-cert
spec:
  commonName: any.common.name
  isCA: true
  dnsNames:
    - '*.stock-trader-cluster-3a99165d2acc3a9ca65ba8c534430045-0000.eu-gb.containers.appdomain.cloud'
  secretName: self-signed-ca-cert
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
