apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-mq-server-cert
spec:
  dnsNames:
    - 'event-cluster-kafka-bootstrap.kafka.svc.cluster.local'
    - 'event-cluster-kafka-brokers.kafka.svc.cluster.local'
    - 'event-cluster-kafka-0.event-cluster-kafka-brokers.kafka.svc.cluster.local'
    - 'event-cluster-kafka-1.event-cluster-kafka-brokers.kafka.svc.cluster.local'
    - 'event-cluster-kafka-2.event-cluster-kafka-brokers.kafka.svc.cluster.local'
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
  secretName: kafka-server-cert
  subject:
    organizations:
    - ibm
