apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db2
  annotations:
    argocd.argoproj.io/sync-wave: "250"
  labels:
    gitops.tier.group: cntk
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: db2
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: 2-services/instances/db2
    repoURL: https://github.com/ldesrosi/stocktrader-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
