apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  annotations:
    argocd.argoproj.io/sync-wave: "230"
  labels:
    gitops.tier.group: cntk
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: 2-services/operators/strimzi-operator
    repoURL: https://github.com/ldesrosi/stocktrader-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
