apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgCaFfzFX0DgwCtjAHqObShUj2Jwhp1f2OvzNIe5IC5Ykc15csrZIRN+vLOlWOKNLsVBxh2boB7oZtT+ck/3OOKUYORfJFbjDBO8RsX4QRzU5I6kJkhe9yhkJHiqes9a9YOcL4sq/ogX/SQcT0KYgdGg3rj93vYJn1Ufn6R+qC9Ff0n7taYCGV030unJgrhBmgwVlpy4yBW1WKFNgZC9vm9UA+lgXg31Nm4ZvWVIVQF9cJHjzNHSnT+l/hQvTGRMzX015CX1sEWcRY9m4myrxE3gHQv7AVRXva5N4Jh5FEizR7Ne5OTZvrckwZkx2SgBpUdM5DvaLRWIx7Jr5ZfLkfXXZOl1pY2JOoAvQjX6CMwAGggdAgK/c2Y+cKEIhk1nGNzJjQ6xA70ZpZZv6izlWeO1XqLeRzg35JmMMl0g1NsGnE3VeuiXH5uhnh68CK+m/sVo1pWbNdavgYPNh5R5GvDkTxdF8gRc9QC2UeOa8QSIgXv+ek9yGg/AVHvpp8jiz3pT5KqQABLhuxXKMJTgad9Kk34aq31A99EJlI4z9iKu1ZQXG0rsb3pWw3DkLI2WbHYajhTXworjDoSI6zpGYowijiwbMCAg1Y5jP1ZJdsjV5ga7J5cR479aMFefqINvM3roadIdEfYH6R9kH3n5NhzP9Z0/SzegPnZKsE7AIPcJvmN4fMWgp86TKzXOmMFIn/7abdEKN9st04+nECI6pwmFDjUIDH/zUlhWM+cFqh2lHNESCDsOdWCBENugbxFYIuf+lnNgIm+LHubx8mcZizJicH5agwAOQpIMLALvPhE7IPBuhibRLHk6TnaRoygvmdMKys85ndI+jJuvjaXvjIm5TpOpcQ7y9ctGF6jqy0SppzguMf40pWOOlDEQyI560fQbsV512K8lS28D8QEOb449kG3l+ML6c8DwYX3iUfCUCI3TV3pcH3t/Bhl9amyFnh8/HpSIIR7yeSxRKerygogjuz4HDLUntuc9p9SjZpZOtfRZ5pT2+7jArLC0W09sdsKoSBS24qhGve9AqbVO/gSAvOkTFURRyqchIpVTiV0z1UYUtyqm1jVLgeEjLlHq2g6E6Z7wHuY3oaaGjb6xiZNBH4RT0Wp+g/WfjWSSahIrhwmJcn3t0AX6u8pjgj/0OStwS6/ki7c8c8Wy3sHYzTIyoVBmYQxZtYTlN2O06Di9q0nkeTFOXcBwuqURc/D9FqFOG7WRqFaGioyOi/Irbk9e4VQ1cvbM/0X/C1oHbB5hte01R9uukKaoFJcmVdSxdVBVXMU8y7hwWbw2fqZpC+vtirNlPywF77My71cV6DdEhiae2zk9CgLXvg6w514X57yq
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: ci
    type: kubernetes.io/dockerconfigjson

