apiVersion: v1
data:
  branch: master
  host: github.com
  org: ldesrosi
  owner: ldesrosi
  parentdir: .
  protocol: https
  repo: stocktrader-gitops
  url: https://github.com/ldesrosi/stocktrader-gitops.git
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
  namespace: ci
